export const AREA_TEMPLATES = {
  newSorpigal: {
    id: "newSorpigal",
    name: "New Sorpigal Outskirts",
    description: "The familiar countryside around New Sorpigal, perfect for beginning adventurers.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["dragonFly", "bandit", "apprenticeMage"],
    boss: "swarm", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "mistyIslands",
    questId: "newSorpigal",
    backgroundImg: "main_bg.webp",
    sideImg: "area-side.webp",
    topImg: "area-top.webp"
  },
  mistyIslands: {
    id: "mistyIslands",
    name: "Misty Islands",
    description: "The familiar countryside around New Sorpigal, perfect for beginning adventurers.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["goblin", "bandit", "apprenticeMage", "skeletonArcher"],
    boss: "goblinKing", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "bootlegBay",
    questId: "mistyIslands",
    backgroundImg: "misty-bg.webp",
    sideImg: "misty-side.webp",
    topImg: "misty-top.webp"
  },
    bootlegBay: {
      id: "bootlegBay",
      name: "Bootleg Bay",
      description: "The islands of Bootleg Bay hide a pile of pirate treasure. That is, if you can get past the cannibals and actually find it.",
      maxWaves: 10,
      //baseLevel: 1,
      enemies: ["pirateRaider", "headHunter", "dustDevil", "giantRat"],
      boss: "seaTerror", 
      //unlocks: ["mistyIslands", "goblinWatch"],
      nextArea: "castleIronfist",
      questId: "bootlegBay",
      backgroundImg: "misty-bg.webp",
      sideImg: "misty-side.webp",
      topImg: "misty-top.webp"
  },
    castleIronfist: {
      id: "castleIronfist",
      name: "Castle Ironfist",
      description: "Ordinarily, we only have one group of bandits preying upon travelers. but these days we have not one, not two, but THREE groups of bandits!",
      maxWaves: 10,
      //baseLevel: 1,
      enemies: ["goblin", "lich", "masterArcher", "bandit", "cobra"],
      boss: "masterThief", 
      //unlocks: ["mistyIslands", "goblinWatch"],
      nextArea: "mireOfTheDamned",
      questId: "castleIronfist",
      backgroundImg: "main_bg.webp",
      sideImg: "area-side.webp",
      topImg: "area-top.webp"
  },
    mireOfTheDamned: {
      id: "mireOfTheDamned",
      name: "Mire of the Damned",
      description: "A mire of the damned!",
      maxWaves: 10,
      //baseLevel: 1,
      enemies: ["spectre", "evilSpirit", "harpy", "skeletonArcher"],
      boss: "snergle", 
      //unlocks: ["mistyIslands", "goblinWatch"],
      nextArea: "freeHaven",
      questId: "mireOfTheDamned",
      backgroundImg: "mire-bg.webp",
      sideImg: "mire-side.webp",
      topImg: "mire-top.webp"
  },
  freeHaven: {
    id: "freeHaven",
    name: "Free Haven",
    description: "Free Haven is the oldest and most prosperous city in the Kingdom.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["dragonFly", "medusa", "emeraldOoze", "royalGriffin"],
    boss: "ethric", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "eelInfestedWaters",
    questId: "freeHaven",
    backgroundImg: "main_bg.webp",
    sideImg: "area-side.webp",
    topImg: "area-top.webp"
  },
  eelInfestedWaters: {
    id: "eelInfestedWaters",
    name: "Eel Infested Waters",
    description: "Be careful of travelling the waters north and east of Silver Cove.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["seaSerpent", "hydra", "waterSpirit" ],
    boss: "frostDrake", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    //nextArea: "mistyIslands",
    questId: "eelInfestedWaters",
    backgroundImg: "misty-bg.webp",
    sideImg: "misty-side.webp",
    topImg: "misty-top.webp"
  },
  // more areas
};
