export const AREA_TEMPLATES = {
  newSorpigal: {
    id: "newSorpigal",
    name: "New Sorpigal Outskirts",
    description: "The familiar countryside around New Sorpigal, perfect for beginning adventurers.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["dragonFly", "bandit", "apprenticeMage"],
    boss: "swarm", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "mistyIslands",
    questId: "newSorpigal",
    backgroundImg: "main_bg.webp",
    sideImg: "area-side.webp",
    topImg: "area-top.webp"
  },
  mistyIslands: {
    id: "mistyIslands",
    name: "Misty Islands",
    description: "The familiar countryside around New Sorpigal, perfect for beginning adventurers.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["goblin", "bandit", "apprenticeMage", "skeletonArcher"],
    boss: "goblinKing", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "bootlegBay",
    questId: "mistyIslands",
    backgroundImg: "misty-bg.webp",
    sideImg: "misty-side.webp",
    topImg: "misty-top.webp"
  },
    bootlegBay: {
      id: "bootlegBay",
      name: "Bootleg Bay",
      description: "The islands of Bootleg Bay hide a pile of pirate treasure. That is, if you can get past the cannibals and actually find it.",
      maxWaves: 10,
      //baseLevel: 1,
      enemies: ["pirateRaider", "headHunter", "dustDevil", "giantRat"],
      boss: "seaTerror", 
      //unlocks: ["mistyIslands", "goblinWatch"],
      nextArea: "castleIronfist",
      questId: "bootlegBay",
      backgroundImg: "misty-bg.webp",
      sideImg: "misty-side.webp",
      topImg: "misty-top.webp"
  },
    castleIronfist: {
      id: "castleIronfist",
      name: "Castle Ironfist",
      description: "Ordinarily, we only have one group of bandits preying upon travelers. but these days we have not one, not two, but THREE groups of bandits!",
      maxWaves: 10,
      //baseLevel: 1,
      enemies: ["goblin", "lich", "masterArcher", "bandit", "cobra"],
      boss: "masterThief", 
      //unlocks: ["mistyIslands", "goblinWatch"],
      nextArea: "mireOfTheDamned",
      questId: "castleIronfist",
      backgroundImg: "main_bg.webp",
      sideImg: "area-side.webp",
      topImg: "area-top.webp"
  },
    mireOfTheDamned: {
      id: "mireOfTheDamned",
      name: "Mire of the Damned",
      description: "A mire of the damned!",
      maxWaves: 10,
      //baseLevel: 1,
      enemies: ["spectre", "evilSpirit", "harpy", "skeletonArcher"],
      boss: "snergle", 
      //unlocks: ["mistyIslands", "goblinWatch"],
      nextArea: "freeHaven",
      questId: "mireOfTheDamned",
      backgroundImg: "mire-bg.webp",
      sideImg: "mire-side.webp",
      topImg: "mire-top.webp"
  },
  freeHaven: {
    id: "freeHaven",
    name: "Free Haven",
    description: "Free Haven is the oldest and most prosperous city in the Kingdom.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["dragonFly", "medusa", "emeraldOoze", "royalGriffin"],
    boss: "ethric", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "eelInfestedWaters",
    questId: "freeHaven",
    backgroundImg: "main_bg.webp",
    sideImg: "area-side.webp",
    topImg: "area-top.webp"
  },
  eelInfestedWaters: {
    id: "eelInfestedWaters",
    name: "Eel Infested Waters",
    description: "Be careful of travelling the waters north and east of Silver Cove.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["seaSerpent", "hydra", "waterSpirit" ],
    boss: "frostDrake", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "silverCove",
    questId: "eelInfestedWaters",
    backgroundImg: "misty-bg.webp",
    sideImg: "misty-side.webp",
    topImg: "misty-top.webp"
  },
  silverCove: {
    id: "silverCove",
    name: "Silver Cove",
    description: "The town of Silver Cove got its start as a fishing and trading village a few hundred years ago.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["diamondGargoyle", "earthElemental", "masterArcher", "druid" ],
    boss: "agarsAbomination", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "frozenHighlands",
    questId: "silverCove",
    backgroundImg: "main_bg.webp",
    sideImg: "area-side.webp",
    topImg: "misty-top.webp"
  },
  frozenHighlands: {
    id: "frozenHighlands",
    name: "Frozen Highlands",
    description: "White Cap is the third largest town in Enroth, and it's been suffering ever since Lord Stromgard lost Icewind Keep to the ogres last year.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["ogre", "harpy", "abomination", "blueDragon" ],
    boss: "captain", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "blackshire",
    questId: "frozenHighlands",
    backgroundImg: "winter-bg.webp",
    sideImg: "winter-side.webp",
    topImg: "winter-top.webp"
  },
  blackshire: {
    id: "blackshire",
    name: "Blackshire",
    description: "The people of Blackshire have fallen under a terrible curse! They turn into werewolves at night.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["werewolf", "apprenticeMage", "dustDevil", "thunderLizard" ],
    boss: "wolfLeader", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "kriegspire",
    questId: "blackshire",
    backgroundImg: "mire-bg.webp",
    sideImg: "mire-side.webp",
    topImg: "mire-top.webp"
  },
  kriegspire: {
    id: "kriegspire",
    name: "Kriegspire",
    description: "Full of the faint smell of brimstone and the faint sound of strange creatures talking in a forgotten language.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["minotaur", "flyingEye", "devilSpawn", "earthElemental" ],
    boss: "fireLizard", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "paradiseValley",
    questId: "kriegspire",
    backgroundImg: "winter-bg.webp",
    sideImg: "winter-side.webp",
    topImg: "winter-top.webp"
  },
  paradiseValley: {
    id: "paradiseValley",
    name: "Paradise Valley",
    description: "Once the greenest and most fertile of lands in Enroth, Pleasant Valley has fallen under a curse that has caused the plants to wither.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["hydra", "evilSpirit", "angel", "emeraldOoze" ],
    boss: "titan", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "hermitIsle",
    questId: "paradiseValley",
    backgroundImg: "sand-bg.webp",
    sideImg: "sand-side.webp",
    topImg: "sand-top.webp"
  },
  hermitIsle: {
    id: "hermitIsle",
    name: "Hermit Island",
    description: "Hermit's Island has recently become home to the Supreme Temple of Baa.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["seaSerpent", "waterSpirit", "lich", "apprenticeMage" ],
    boss: "efreet", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "dragonSand",
    questId: "hermitIsle",
    backgroundImg: "misty-bg.webp",
    sideImg: "misty-side.webp",
    topImg: "misty-top.webp"
  },
  dragonSand: {
    id: "dragonSand",
    name: "Dragon Sand",
    description: "Dragonsand, the great desert of Enroth, is home to all the worst monsters in the world.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["blueDragon", "thunderLizard", "diamondGargoyle", "giant"],
    boss: "goldDragon", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    nextArea: "sweetWater",
    questId: "dragonSand",
    backgroundImg: "sand-bg.webp",
    sideImg: "sand-side.webp",
    topImg: "sand-top.webp"
  },
  sweetWater: {
    id: "sweetWater",
    name: "Sweet Water",
    description: "Sweet Water used to be the most beautiful town in the kingdom, but no news has come from it since the Night of Shooting Stars.",
    maxWaves: 10,
    //baseLevel: 1,
    enemies: ["angel", "flyingEye", "devilSpawn", "fireElemental"],
    boss: "demonQueen", 
    //unlocks: ["mistyIslands", "goblinWatch"],
    //nextArea: "mistyIslands",
    questId: "dragonSand",
    backgroundImg: "mire-bg.webp",
    sideImg: "mire-side.webp",
    topImg: "mire-top.webp"
  },
  // more areas
};
