export const classes = [
    { id: "fighter", 
      name: "Fighter",
      level: 1, 
      goldCost: 10,
      gemCost: 0, 
      goldIncomePerHit: 0.5, 
      gemPerSecond: 0,
      buildingRequired: null,
      image: "../assets/images/classes/fighter.png",
      description: "Scrappy brawler that gains damage per hit to the same target and pressures columns.",
      abilities: [
        { id: "pummel", unlockLevel: 1 },
        { id: "followThrough", unlockLevel: 1 },
        { id: "speedBoost", unlockLevel: 5 }
      ],
      skills: {
        pummel: { active: true },
        followThrough: { cooldownRemaining: 7000 },
        speedBoost: { active: false, streak: 0 }
      },
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "physical",
      baseStats: { hp: 15, mp: 0, attack: 4, defense: 3, criticalChance: 0.15, speed: 1 },
      growthPerLevel: { hp: 1, mp: 0, attack: 1, defense: 1 },
      attackCooldown: 0
    },
    { id: "knight", 
      name: "Knight", 
      goldCost: 20,
      gemCost: 0, 
      goldIncomePerHit: 0.5, 
      buildingRequired: { id: "barracks", level: 1 }, 
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "physical",
      baseStats: { hp: 20, mp: 0, attack: 4, defense: 3, criticalChance: 0.15, speed: 1.5 },
      growthPerLevel: { hp: 1, mp: 0, attack: 1, defense: 1 },
      abilities: [
        { id: "leadership", unlockLevel: 1 },
        { id: "flameArch", unlockLevel: 1 }
        
      ],
      skills: {
        leadership: { active: true },
        flameArch: { cooldownRemaining: 6500 }
      },
      attackCooldown: 0
    },
    { id: "mage", 
      name: "Mage", 
      level: 1,
      goldCost: 30,
      gemCost: 5, 
      goldIncomePerHit: 0.5, 
      gemPerSecond: 0,
      buildingRequired: {
        id: "mageGuild", level: 1 },
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "fire",
      baseStats: { hp: 10, mp: 10, attack: 6, defense: 2, criticalChance: 0.1, speed: 1.2 },
      growthPerLevel: { hp: 1, mp: 2, attack: 2, defense: 1 },
      attackCooldown: 0 
    },
    { id: "rogue", 
      name: "Rogue", 
      level: 1,
      goldCost: 25,
      gemCost: 0, 
      goldIncomePerHit: 1,
      gemPerSecond: 0, 
      buildingRequired: {id: "thievesGuild", level: 1 },
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "physical",
      abilities: [
        { id: "weakSpot", unlockLevel: 1 },
        { id: "poisonFlask", unlockLevel: 1 },
        { id: "lethalDose", unlockLevel: 5 }
      ],
      skills: {
        weakSpot: { active: true },
        poisonFlask: { cooldownRemaining: 8000 },
        lethalDose: { active: false }
      },
      baseStats: { hp: 12, mp: 5, attack: 5, defense: 2, criticalChance: 0.2, speed: 1.8 },
      growthPerLevel: { hp: 1, mp: 1, attack: 1, defense: 1 },
      attackCooldown: 0
    },
    { id: "cleric", 
      name: "Cleric", 
      level: 1,
      goldCost: 35,
      gemCost: 0, 
      goldIncomePerHit: 0.5,
      gemPerSecond: 0, 
      buildingRequired: {id: "temple", level: 1 },
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "light",
      baseStats: { hp: 14, mp: 8, attack: 4, defense: 3, criticalChance: 0.1, speed: 1.3 },
      growthPerLevel: { hp: 1, mp: 2, attack: 1, defense: 1 },
      attackCooldown: 0
    },
    { id: "necromancer", 
      name: "Necromancer",
      image: "../assets/images/classes/necromancer.png", 
      level: 1,
      goldCost: 60,
      gemCost: 0, 
      goldIncomePerHit: 0.5,
      gemPerSecond: 0, 
      buildingRequired: [
        {id: "mageGuild", level: 1 },
        {id: "darkTower", level: 1 }
      ],
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "dark",
      baseStats: { hp: 12, mp: 15, attack: 7, defense: 2, criticalChance: 0.1, speed: 1.2 },
      growthPerLevel: { hp: 1, mp: 3, attack: 2, defense: 1 },
      attackCooldown: 0
    }, 
    { id: "druid", 
      name: "Druid", 
      image: "../assets/images/classes/druid.png",
      level: 1,
      goldCost: 30,
      gemCost: 10, 
      goldIncomePerHit: 0.5, 
      gemPerSecond: 0.0167, // 1 gem per minute
      buildingRequired: {id: "grove", level: 1 },
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "earth",
      baseStats: { hp: 12, mp: 12, attack: 5, defense: 3, criticalChance: 0.1, speed: 1.3 },
      growthPerLevel: { hp: 1, mp: 2, attack: 1, defense: 1 },
      attackCooldown: 0
    },
    { id: "paladin", 
      name: "Paladin", 
      image: "../assets/images/classes/paladin.png",
      level: 1,
      goldCost: 50,
      gemCost: 5, 
      goldIncomePerHit: 0.5, 
      gemPerSecond: 0.0167, // 1 gem per minute
      buildingRequired: [
        {id: "barracks", level: 5 },
        {id: "temple", level: 5} 
      ],
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "light",
      baseStats: { hp: 25, mp: 5, attack: 5, defense: 5, criticalChance: 0.1, speed: 1.2 },
      growthPerLevel: { hp: 2, mp: 1, attack: 1, defense: 2 },
      attackCooldown: 0
    },
    { id: "archer", 
      name: "Archer", 
      image: "../assets/images/classes/archer.png",
      level: 1,
      goldCost: 40,
      gemCost: 0, 
      goldIncomePerHit: 0.5,
      gemPerSecond: 0, 
      buildingRequired: {id: "archery", level: 1},
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "physical",
      baseStats: { hp: 12, mp: 5, attack: 6, defense: 2, criticalChance: 0.15, speed: 1.5 },
      growthPerLevel: { hp: 1, mp: 1, attack: 1, defense: 1 },
      attackCooldown: 0 
    },
    { id: "ranger", 
      name: "Ranger", 
      image: "../assets/images/classes/ranger.png",
      level: 1,
      goldCost: 55,
      gemCost: 5, 
      goldIncomePerHit: 1,
      gemPerSecond: 0.0167, // 1 gem per minute 
      buildingRequired: [
        {id: "archery", level: 5 },
        {id: "grove", level: 1 },
        { id: "thievesGuild", level: 5 }
      ],
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "physical",
      baseStats: { hp: 15, mp: 8, attack: 7, defense: 3, criticalChance: 0.15, speed: 1.6 },
      growthPerLevel: { hp: 1, mp: 1, attack: 1, defense: 1 },
      attackCooldown: 0 
    },
    { 
      id: "assassin", 
      name: "Assassin", 
      image: "../assets/images/classes/assassin.png",
      level: 1,
      goldCost: 70,
      gemCost: 5, 
      goldIncomePerHit: 1,
      gemPerSecond: 0, 
      buildingRequired: [
        {id: "thievesGuild", level: 10 },
        {id: "darkTower", level: 1 }
      ],
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "dark",
      baseStats: { hp: 14, mp: 8, attack: 8, defense: 2, criticalChance: 0.25, speed: 1.8 },
      growthPerLevel: { hp: 1, mp: 1, attack: 2, defense: 1 },
      attackCooldown: 0 
    }
];
