import { partyState } from "../state.js";

export const classes = [
    { id: "fighter", 
      name: "Fighter",
      level: 0, 
      goldCost: 10,
      gemCost: 0, 
      goldIncomePerHit: 0.5, 
      gemPerSecond: 0,
      buildingRequired: { id: "farm", level: 1 },
      hasAutoAttack: true,
      //image: "assets/images/classes/fighter.png",
      description: "Scrappy brawler that gains damage per hit to the same target and pressures columns.",
      abilities: [
        { id: "pummel", unlockLevel: 1 },
        { id: "followThrough", unlockLevel: 1, active: false },
        { id: "speedBoost", unlockLevel: 5 }
      ],
      skills: {
        pummel: { active: true },
        followThrough: { cooldownRemaining: 7000 },
        speedBoost: { active: false, streak: 0 }
      },
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "physical",
      baseStats: { hp: partyState.heroStats.hp, attack: partyState.heroStats.attack, defense: 3, criticalChance: 0.15, speed: 1 },
      growthPerLevel: { attack: 1, defense: 1 },
      attackCooldown: 0
    },
    { id: "knight", 
      name: "Knight", 
      goldCost: 20,
      gemCost: 0, 
      goldIncomePerHit: 0.5, 
      buildingRequired: { id: "barracks", level: 1 }, 
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "physical",
      hasAutoAttack: true,
      baseStats: { hp: partyState.heroStats.hp * 1.2, attack: partyState.heroStats.attack * 0.8, defense: 3, criticalChance: 0.15, speed: 1.5 },
      growthPerLevel: { attack: 1, defense: 1 },
      abilities: [
        { id: "leadership", unlockLevel: 1 },
        { id: "flameArch", unlockLevel: 1, active: false }
        
      ],
      skills: {
        leadership: { active: true },
        flameArch: { cooldownRemaining: 6500 }
      },
      attackCooldown: 0
    },
    { id: "mage", 
      name: "Mage", 
      level: 0,
      goldCost: 30,
      gemCost: 5, 
      goldIncomePerHit: 0.5, 
      gemPerSecond: 0,
      buildingRequired: {
        id: "mageGuild", level: 1 },
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "fire",
      hasAutoAttack: true,
      baseStats: { hp: partyState.heroStats.hp * 0.5, attack: partyState.heroStats.attack * 1.5, defense: 2, criticalChance: 0.1, speed: 1.2 },
      growthPerLevel: { attack: 2, defense: 1 },
      attackCooldown: 0 
    },
    { id: "rogue", 
      name: "Rogue", 
      level: 0,
      goldCost: 25,
      gemCost: 0, 
      goldIncomePerHit: 1,
      gemPerSecond: 0, 
      buildingRequired: {id: "thievesGuild", level: 1 },
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "physical",
      hasAutoAttack: true,
      abilities: [
        { id: "weakSpot", unlockLevel: 1 },
        { id: "poisonFlask", unlockLevel: 1, active: false },
        { id: "lethalDose", unlockLevel: 5 }
      ],
      skills: {
        weakSpot: { active: true },
        poisonFlask: { cooldownRemaining: 8000 },
        lethalDose: { active: false }
      },
      baseStats: { hp: partyState.heroStats.hp * 0.7, attack: partyState.heroStats.attack * 1.3, defense: 2, criticalChance: 0.2, speed: 1.8 },
      growthPerLevel: { attack: 1, defense: 1 },
      attackCooldown: 0
    },
    { id: "cleric", 
      name: "Cleric", 
      level: 0,
      goldCost: 35,
      gemCost: 0, 
      goldIncomePerHit: 0.5,
      gemPerSecond: 0, 
      buildingRequired: {id: "temple", level: 1 },
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "light",
      hasAutoAttack: true,
      baseStats: { hp: partyState.heroStats.hp * 1.1, attack: partyState.heroStats.attack * 0.8, defense: 3, criticalChance: 0.1, speed: 1.3 },
      growthPerLevel: { attack: 1, defense: 1 },
      attackCooldown: 0,
      abilities: [
        { id: "summonAngel", unlockLevel: 5, active: false },        
      ],
      skills: {
        summonAngel: { cooldownRemaining: 20000 },
      },
    },
    { id: "templar", 
      name: "Templar", 
      goldCost: 20,
      gemCost: 0, 
      level: 0,
      goldIncomePerHit: 0.5, 
      buildingRequired: [
        { id: "bellTower", level: 1 }, 
      ],
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "light",
      hasAutoAttack: true,
      baseStats: { hp: partyState.heroStats.hp * 1.2, attack: partyState.heroStats.attack * 0.8, defense: 3, criticalChance: 0.15, speed: 1.5 },
      growthPerLevel: { attack: 1, defense: 1 },
      abilities: [
        { id: "blindingLight", unlockLevel: 1 },
        
      ],
      skills: {
        blindingLight: { active: true },
      },
      attackCooldown: 0
    },    
    { id: "necromancer", 
      name: "Necromancer",
     //image: "assets/images/classes/necromancer.png", 
      level: 0,
      goldCost: 60,
      gemCost: 0, 
      goldIncomePerHit: 0.5,
      gemPerSecond: 0, 
      buildingRequired: [
        {id: "mageGuild", level: 1 },
        {id: "darkTower", level: 1 }
      ],
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "dark",
      hasAutoAttack: false,
      baseStats: { hp: partyState.heroStats.hp * 0.9, attack: 0, defense: 2, criticalChance: 0.1, speed: 1.2 },
      growthPerLevel: { attack: 0, defense: 1 },
      attackCooldown: 0
    }, 
    { id: "druid", 
      name: "Druid", 
     //image: "assets/images/classes/druid.png",
      level: 0,
      goldCost: 30,
      gemCost: 10, 
      goldIncomePerHit: 0.5, 
      gemPerSecond: 0.0167, // 1 gem per minute
      buildingRequired: {id: "grove", level: 1 },
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "earth",
      hasAutoAttack: false,
      baseStats: { hp: partyState.heroStats.hp * 0.9, attack: partyState.heroStats.attack * 1.1, defense: 3, criticalChance: 0.1, speed: 1.3 },
      growthPerLevel: { attack: 1, defense: 1 },
      attackCooldown: 0,
      abilities: [
        { id: "landslide", unlockLevel: 1, active: false },
        { id: "summonWaterElemental", unlockLevel: 1, active: false },
        { id: "earthquake", unlockLevel: 5, active: false },
        
      ],
      skills: {
        landslide: { cooldownRemaining: 8000 },
        summonWaterElemental: { cooldownRemaining: 25000 },
        earthquake: { cooldownRemaining: 22000 }
      },
    },
    { id: "archer", 
      name: "Archer", 
     //image: "assets/images/classes/archer.png",
      level: 0,
      goldCost: 40,
      gemCost: 0, 
      goldIncomePerHit: 0.5,
      gemPerSecond: 0, 
      buildingRequired: {id: "archery", level: 1},
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "air",
      hasAutoAttack: true,
      baseStats: { hp: partyState.heroStats.hp * 0.6, attack: partyState.heroStats.attack * 1.2, defense: 2, criticalChance: 0.15, speed: 1.5 },
      growthPerLevel: { attack: 1, defense: 1 },
      attackCooldown: 0,
      abilities: [
        { id: "sparks", unlockLevel: 1, active: false },
        { id: "falconer", unlockLevel: 5, active: false },        
      ],
      skills: {
        sparks: { cooldownRemaining: 8000 },
        falconer: { cooldownRemaining: 11000 },
      }, 
    },
    /* 
    { id: "ranger", 
      name: "Ranger", 
      image: "assets/images/classes/ranger.png",
      level: 0,
      goldCost: 55,
      gemCost: 5, 
      goldIncomePerHit: 1,
      gemPerSecond: 0.0167, // 1 gem per minute 
      buildingRequired: [
        {id: "archery", level: 5 },
        {id: "grove", level: 1 },
        { id: "thievesGuild", level: 5 }
      ],
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "physical",
      hasAutoAttack: true,
      baseStats: { hp: partyState.heroStats.hp * 0.6, attack: partyState.heroStats.attack * 1.2, defense: 2, criticalChance: 0.15, speed: 1.6 },
      growthPerLevel: { attack: 1, defense: 1 },
      attackCooldown: 0 
    },
    { 
      id: "assassin", 
      name: "Assassin", 
      image: "assets/images/classes/assassin.png",
      level: 0,
      goldCost: 70,
      gemCost: 5, 
      goldIncomePerHit: 1,
      gemPerSecond: 0, 
      buildingRequired: [
        {id: "thievesGuild", level: 10 },
        {id: "darkTower", level: 1 }
      ],
      lastTarget: null,
      sameTargetStreak: 0,
      resonance: "dark",
      hasAutoAttack: true,
      baseStats: { hp: partyState.heroStats.hp * 0.7, attack: partyState.heroStats.attack * 1.3, defense: 2, criticalChance: 0.15, speed: 1.8 },
      growthPerLevel: { attack: 2, defense: 1 },
      attackCooldown: 0 
    }
      */
];
