export const ENEMY_TEMPLATES = {
  // Basic Enemies
  dragonFly: {
    id: "dragonFly",
    baseName: "Dragon Fly",
    type: "pest",
    elementType: "pest",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: [],
    image: "assets/images/enemies/dragonFly.webp",
    weaknesses: ["physical"],
    description: "Nuisance dragon flies common throughout the land."
  },
  goblin: {
    id: "goblin",
    baseName: "Goblin",
    type: "humanoid",
    elementType: "poison",
    tier: 1,
    speed: 1.5,
    maxMp: 20,
    row: 0,
    image: "assets/images/enemies/goblin.webp",
    hpFormula: (level) => Math.floor(10 + level * (Math.random() * 2 + 25) + Math.pow(level, 1.2) * 4),
    attackFormula: (level) => Math.floor(3 + level * 1.2),
    xpFormula: (level) => Math.floor(20 * Math.pow(1.13, level - 1)),
    description: "A small, green humanoid creature known for its cunning and mischief.",
    resistances: ["physical"],
    weaknesses: ["water"]
  },
   bandit: {
    id: "bandit",
    baseName: "Bandit",
    type: "humanoid",
    elementType: "physical",
    tier: 1,
    dodge: .30,
    speed: 2.5,
    row: 1,
    image: "assets/images/enemies/bandit.webp",
    hpFormula: (level) => Math.floor(15 + level * (Math.random() * 2 + 25) + Math.pow(level, 1.2) * 5),
    attackFormula: (level) => Math.floor(4 + level * 1.3),
    goldFormula: (level) => Math.floor(14 + level * 3),
    xpFormula: (level) => Math.floor(20 * Math.pow(1.13, level - 1)),
    resistances: ["pest"],
    weaknesses: ["poison", "undead"]
    //variants: ["Thief", "Outlaw", "Captain"]
  },
  
  apprenticeMage: {
    id: "apprenticeMage",
    baseName: "Apprentice Mage",
    type: "humanoid",
    elementType: "fire",
    tier: 1,
    speed: 1.5,
    row: 2,
    isMagic: true,
    image: "assets/images/enemies/mage.webp",
    hpFormula: (level) => Math.floor(20 + level * (Math.random() * 2 + 25) + Math.pow(level, 1.2) * 5),
    attackFormula: (level) => Math.floor(7 + level * 1.4),
    goldFormula: (level) => Math.floor(10 + level * 1.5),
    xpFormula: (level) => Math.floor(20 * Math.pow(1.13, level - 1)),
    resistances: ["earth", "undead"],
    weaknesses: ["water"]
  },
    skeletonArcher: {
    id: "skeletonArcher",
    baseName: "Skeleton Archer",
    type: "undead",
    elementType: "undead",
    tier: 1,
    speed: 1.5,
    row: 2,
    isMagic: false,
    image: "assets/images/enemies/skeletonArcher.webp",
    hpFormula: (level) => Math.floor(20 + level * (Math.random() * 2 + 25) + Math.pow(level, 1.2) * 5),
    attackFormula: (level) => Math.floor(7 + level * 1.4),
    goldFormula: (level) => Math.floor(10 + level * 1.5),
    xpFormula: (level) => Math.floor(20 * Math.pow(1.13, level - 1)),
    resistances: ["physical"],
    weaknesses: ["light", "fire", "water"]
  },
  giantRat: {
    id: "giantRat",
    baseName: "Giant rat",
    type: "pest",
    elementType: "pest",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: [],
    image: "assets/images/enemies/giantRat.webp",
    weaknesses: ["physical"],
    description: "Nuisance rats common throughout the land."
  },
  pirateRaider: {
    id: "pirateRaider",
    baseName: "Pirate raider",
    type: "humanoid",
    elementType: "water",
    tier: 2,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["fire", "poison"],
    image: "assets/images/enemies/pirateRaider.webp",
    weaknesses: ["air"],
    description: "Nuisance pirates common throughout the land."
  },
  headHunter: {
    id: "headHunter",
    baseName: "Head hunter",
    type: "humanoid",
    elementType: "dark",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: [],
    image: "assets/images/enemies/deathKnight.webp",
    weaknesses: ["light"],
    description: "Nuisance headhunters common throughout the land."
  },
  dustDevil: {
    id: "dustDevil",
    baseName: "Dust devil",
    type: "elemental",
    elementType: "air",
    tier: 2,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["water"],
    image: "assets/images/enemies/willow.webp",
    weaknesses: ["earth"],
    description: "Nuisance dust devil common throughout the land."
  },
  cobra: {
    id: "cobra",
    baseName: "cobra",
    type: "pest",
    elementType: "pest",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: [],
    image: "assets/images/enemies/cobra.webp",
    weaknesses: ["physical"],
    description: "Nuisance cobras common throughout the land."
  },
  masterArcher: {
    id: "masterArcher",
    baseName: "Master Archer",
    type: "humanoid",
    elementType: "air",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["water"],
    image: "assets/images/enemies/masterArcher.webp",
    weaknesses: ["earth"],
    description: "Nuisance master archers common throughout the land."
  },
  lich: {
    id: "lich",
    baseName: "Lich",
    type: "humanoid",
    elementType: "undead",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["physical"],
    image: "assets/images/enemies/lich.webp",
    weaknesses: ["light", "fire", "water"],
    description: "Nuisance liches common throughout the land."
  },
  harpy: {
    id: "harpy",
    baseName: "Harpy",
    type: "beast",
    elementType: "dark",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["??"],
    image: "assets/images/enemies/harpy.webp",
    weaknesses: ["??"],
    description: "Nuisance harpy common throughout the land."
  },
  spectre: {
    id: "spectre",
    baseName: "Spectre",
    type: "undead",
    elementType: "air",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["water"],
    image: "assets/images/enemies/spectre.webp",
    weaknesses: ["earth"],
    description: "Nuisance spectre common throughout the land."
  },
  emeraldOoze: {
    id: "emeraldOoze",
    baseName: "Emerald Ooze",
    type: "elemental",
    elementType: "poison",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["physical"],
    image: "assets/images/enemies/emeraldOoze.webp",
    weaknesses: ["water"],
    description: "Nuisance emerald ooze common throughout the land."
  },
  medusa: {
    id: "medusa",
    baseName: "Medusa",
    type: "beast",
    elementType: "earth",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["fire"],
    image: "assets/images/enemies/medusa.webp",
    weaknesses: ["air"],
    description: "Nuisance medusa common throughout the land."
  },
  royalGriffin: {
    id: "royalGriffin",
    baseName: "Royal Griffin",
    type: "beast",
    elementType: "air",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["water"],
    image: "assets/images/enemies/royalGriffin.webp",
    weaknesses: ["earth"],
    description: "Nuisance royal griffin common throughout the land."
  },
  evilSpirit: {
    id: "evilSpirit",
    baseName: "Evil Spirit",
    type: "elemental",
    elementType: "undead",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["physical"],
    image: "assets/images/enemies/willow.webp",
    weaknesses: ["light", "fire", "water"],
    description: "Nuisance spectre common throughout the land."
  },
  spider: {
    id: "spider",
    baseName: "spider",
    type: "pest",
    elementType: "pest",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: [],
    image: "assets/images/enemies/spider.webp",
    weaknesses: ["physical"],
    description: "Nuisance spiders common throughout the land."
  },
    seaSerpent: {
      id: "seaSerpent",
      baseName: "Sea Serpent",
            type: "beast",
      elementType: "water",
      tier: 1,
      isBoss: false,
      maxMp: 30,
      resistances: ["fire"],
      image: "assets/images/enemies/seaTerror.webp",
      weaknesses: ["air"]
    },
    waterSpirit: {
      id: "waterSpirit",
      baseName: "Water Spirit",
      type: "elemental",
      elementType: "water",
      tier: 1,
      speed: 2,
      maxMp: 15,
      row: 0,
      resistances: ["fire"],
      image: "assets/images/enemies/waterSpirit.webp",
      weaknesses: ["air"],
      description: "Nuisance water spirit common throughout the land."
  },
  hydra: {
    id: "hydra",
    baseName: "hydra",
    type: "beast",
    elementType: "poison",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["physical"],
    image: "assets/images/enemies/hydra.webp",
    weaknesses: ["water"],
    description: "Nuisance hydra common throughout the land."
  },
  diamondGargoyle: {
    id: "diamondGargoyle",
    baseName: "Diamond Gargoyle",
    type: "construct",
    elementType: "earth",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["air"],
    image: "assets/images/enemies/diamondGargoyle.webp",
    weaknesses: ["fire"],
    description: "Nuisance gargoyle common throughout the land."
  },
  earthElemental: {
    id: "earthElemental",
    baseName: "Earth Elemental",
    type: "elemental",
    elementType: "earth",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["air"],
    image: "assets/images/enemies/earthElemental.webp",
    weaknesses: ["fire"],
    description: "Nuisance earth elemental common throughout the land."
  },
  druid: {
    id: "druid",
    baseName: "Druid",
    type: "humanoid",
    elementType: "earth",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["air"],
    image: "assets/images/enemies/warlock.webp",
    weaknesses: ["fire"],
    description: "Nuisance druid common throughout the land."
  },
  ogre: {
    id: "ogre",
    baseName: "Ogre",
    type: "humanoid",
    elementType: "physical",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["pest"],
    image: "assets/images/enemies/ogre.webp",
    weaknesses: ["poison", "undead"],
    description: "Nuisance ogre common throughout the land."
  },
  abomination: {
    id: "abomination",
    baseName: "Abomination",
    type: "construct",
    elementType: "undead",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["poison", "physical"],
    image: "assets/images/enemies/chimera.webp",
    weaknesses: ["fire", "water", "light"],
    description: "Nuisance abomination common throughout the land."
  },
  blueDragon: {
    id: "blueDragon",
    baseName: "Blue Dragon",
    type: "dragon",
    elementType: "water",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["fire", "undead"],
    image: "assets/images/enemies/frostDrake.webp",
    weaknesses: ["air"],
    description: "Nuisance blue dragon common throughout the land."
  },
  werewolf: {
    id: "werewolf",
    baseName: "Werewolf",
    type: "beast",
    elementType: "physical",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["pest"],
    image: "assets/images/enemies/werewolf.webp",
    weaknesses: ["undead", "poison"],
    description: "Nuisance werewolf common throughout the land."
  },
  thunderLizard: {
    id: "thunderLizard",
    baseName: "Thunder Lizard",
    type: "dragon",
    elementType: "air",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["water"],
    image: "assets/images/enemies/goldDragon.webp",
    weaknesses: ["earth"],
    description: "Nuisance thunder lizard common throughout the land."
  },
  minotaur: {
    id: "minotaur",
    baseName: "Minotaur",
    type: "humanoid",
    elementType: "earth",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["air"],
    image: "assets/images/enemies/minotaur.webp",
    weaknesses: ["fire"],
    description: "Nuisance minotaur common throughout the land."
  },
  giant: {
    id: "giant",
    baseName: "Giant",
    type: "construct",
    elementType: "earth",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["air"],
    image: "assets/images/enemies/titan.webp",
    weaknesses: ["fire"],
    description: "Nuisance giants common throughout the land."
  },
  flyingEye: {
    id: "flyingEye",
    baseName: "Flying Eye",
    type: "construct",
    elementType: "dark",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["??"],
    image: "assets/images/enemies/flyingEye.webp",
    weaknesses: ["??"],
    description: "Nuisance flying eye common throughout the land."
  },
  devilSpawn: {
    id: "devilSpawn",
    baseName: "Devil Spawn",
    type: "demon",
    elementType: "dark",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["??"],
    image: "assets/images/enemies/devilSpawn.webp",
    weaknesses: ["??"],
    description: "Nuisance devil spawn common throughout the land."
  },
  angel: {
    id: "angel",
    baseName: "Angel",
    type: "elemental",
    elementType: "light",
    tier: 1,
    speed: 2,
    maxMp: 15,
    row: 0,
    resistances: ["??"],
    image: "assets/images/enemies/angel.webp",
    weaknesses: ["??"],
    description: "Nuisance angel common throughout the land."
  },
  // Boss Enemies
    swarm: {
      id: "swarm",
      baseName: "Swarm",
      type: "pest",
      elementType: "pest",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: [],
      image: "assets/images/enemies/swarm.webp",
      weaknesses: ["physical"]
    },
    efreet: {
      id: "efreet",
      baseName: "Efreet",
      type: "elemental",
      elementType: "fire",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["earth"],
      image: "assets/images/enemies/efreet.webp",
      weaknesses: ["water"]
    },
    titan: {
      id: "titan",
      baseName: "Titan",
      type: "construct",
      elementType: "physical",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["pest"],
      image: "assets/images/enemies/titan.webp",
      weaknesses: ["undead", "poison"]
    },
    captain: {
      id: "captain",
      baseName: "Captain",
      type: "humanoid",
      elementType: "poison",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["physical"],
      image: "assets/images/enemies/minotaur.webp",
      weaknesses: ["water"]
    },
    demonQueen: {
      id: "demonQueen",
      baseName: "Demon Queen",
      type: "demon",
      elementType: "dark",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["??"],
      image: "assets/images/enemies/demonQueen.webp",
      weaknesses: ["??"]
    },
    wolfLeader: {
      id: "wolfLeader",
      baseName: "Wolf Leader",
      type: "beast",
      elementType: "dark",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["??"],
      image: "assets/images/enemies/werewolf.webp",
      weaknesses: ["??"]
    },
    fireLizard: {
      id: "fireLizard",
      baseName: "Fire Lizard",
      type: "dragon",
      elementType: "fire",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["earth"],
      image: "assets/images/enemies/basilisk.webp",
      weaknesses: ["water"]
    },
    goldDragon: {
      id: "goldDragon",
      baseName: "Gold Dragon",
      type: "dragon",
      elementType: "light",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["??"],
      image: "assets/images/enemies/goldDragon.webp",
      weaknesses: ["??"]
    },
    ethric: {
      id: "ethric",
      baseName: "Ethric",
      type: "humanoid",
      elementType: "undead",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["physical"],
      image: "assets/images/enemies/lich.webp",
      weaknesses: ["light", "fire", "water"]
    },
    frostDrake: {
      id: "frostDrake",
      baseName: "Frost Drake",
      type: "dragon",
      elementType: "water",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["fire"],
      image: "assets/images/enemies/frostDrake.webp",
      weaknesses: ["air"]
    },
    agarsAbomination: {
      id: "agarsAbomination",
      baseName: "Agar's Abomination",
      type: "undead",
      elementType: "air",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["water"],
      image: "assets/images/enemies/chimera.webp",
      weaknesses: ["earth"]
    },
    goblinKing: {
    id: "goblinKing",
    baseName: "Goblin King",
    type: "humanoid",
    elementType: "poison",
    tier: "boss",
    isBoss: true,
    lootTier: 4,
    maxMp: 40,
    hpFormula: (level) => Math.floor((20 + level * (Math.random() * 2 + 25) + Math.pow(level, 1.2) * 5) * 2),
    attackFormula: (level) => Math.floor(12 + level * 2.5),
    goldFormula: (level) => Math.floor(60 + level * 3),
    xpFormula: (level) => Math.floor(30 * Math.pow(1.13, level - 1)),
    variants: ["Warlord", "Tyrant", "Destroyer"],
    resistances: ["physical"],
    weaknesses: ["water"],
    image: "assets/images/enemies/goblinKing.webp",
    description: "The Goblin King is a formidable leader of goblin tribes, known for his cunning tactics and ruthless nature.",
    // Special abilities
    specialAbilities: [{
      type: "summon",
      summonId: "goblin",   // what to summon
      interval: 7500,             // every 7.5s
      max: 2,                      // maximum alive
      cost: 20
    }]
    },
    seaTerror: {
      id: "seaTerror",
      baseName: "Sea Terror",
            type: "beast",
      elementType: "water",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["fire"],
      image: "assets/images/enemies/seaTerror.webp",
      weaknesses: ["air"]
    },
    masterThief: {
      id: "masterThief",
      baseName: "Master thief",
      type: "humanoid",
      elementType: "physical",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["pest"],
      image: "assets/images/enemies/thief.webp",
      weaknesses: ["poison", "undead"]
    },
    snergle: {
      id: "snergle",
      baseName: "Snergle",
      type: "humanoid",
      elementType: "earth",
      tier: "boss",
      isBoss: true,
      maxMp: 30,
      resistances: ["air"],
      image: "assets/images/enemies/snergle.webp",
      weaknesses: ["fire"]
    },
};

// Higher tier enemies can be defined similarly
// e.g., bandit, apprenticeMage, goblinKing, etc.
